"""Initial migration.

Revision ID: 4f97e065bd94
Revises: 
Create Date: 2024-11-08 19:06:59.838710

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4f97e065bd94'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('take_away_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('table_reservation_start_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('table_reservation_end_time', sa.DateTime(), nullable=True))
        batch_op.alter_column('table_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('update_date')
        batch_op.drop_column('take_away')

    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('take_away', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('update_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.alter_column('table_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('table_reservation_end_time')
        batch_op.drop_column('table_reservation_start_time')
        batch_op.drop_column('take_away_time')

    # ### end Alembic commands ###
