"""Added description do Employees

Revision ID: 646963c6de9f
Revises: 8efad068c356
Create Date: 2024-12-29 20:09:14.738724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '646963c6de9f'
down_revision = '8efad068c356'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
