"""Changed reviews stars type.

Revision ID: 678257380233
Revises: 4f97e065bd94
Create Date: 2024-11-08 19:09:25.912815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '678257380233'
down_revision = '4f97e065bd94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('stars',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('stars',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
