"""Deleted table is_available column.

Revision ID: 8efad068c356
Revises: a4be0aa36733
Create Date: 2024-11-14 20:42:28.226881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8efad068c356'
down_revision = 'a4be0aa36733'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.drop_column('is_available')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_available', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
