"""Changed dishes character varying sizes.

Revision ID: a4be0aa36733
Revises: fd98d040955d
Create Date: 2024-11-11 15:01:34.523159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4be0aa36733'
down_revision = 'fd98d040955d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dishes', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=70),
               type_=sa.String(length=250),
               existing_nullable=False)
        batch_op.alter_column('photo_url',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=2500),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=350),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dishes', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=350),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False)
        batch_op.alter_column('photo_url',
               existing_type=sa.String(length=2500),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=70),
               existing_nullable=False)

    # ### end Alembic commands ###
