"""Deleted ingredient_id from dishes table.

Revision ID: fd98d040955d
Revises: 678257380233
Create Date: 2024-11-11 14:51:52.067162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd98d040955d'
down_revision = '678257380233'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dishes', schema=None) as batch_op:
        batch_op.drop_constraint('dishes_ingredient_id_fkey', type_='foreignkey')
        batch_op.drop_column('ingredient_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dishes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingredient_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('dishes_ingredient_id_fkey', 'ingredients', ['ingredient_id'], ['ingredient_id'])

    # ### end Alembic commands ###
